// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeEntity.Entity
{
    public partial class Locations
    {
        public Locations()
        {
            Detail = new HashSet<Detail>();
        }

        public int Location_Id { get; set; }
        public string Location { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Create_Time_Stamp { get; set; }
        public DateTime Update_Time_Stamp { get; set; }

        public virtual ICollection<Detail> Detail { get; set; }
    }
}